import { createStore } from 'vuex'

export default createStore({
  state: {
    registros: [
      "Fulano",
      "Cicrano",
      "Beltrano",
      "Zezinho",
      "Galvão",
      "Sr. Bola",
      "Maria do Carmo",
      "Ana",
      "João",
      "Pedro",
      "Maria",
      "Francisco",
      "Catarina Santis",
      "Catarina Santus",
      "Catarina Santes",
      "Catarina Santos",
      "Carlos",
      "José",
      "Margarida",
      "António",
      "Luís",
      "Paulo",
      "Isabel",
      "Eduardo",
      "Rafael",
      "Miguel",
      "Sofia",
      "Bruno",
      "André",
      "Diana",
      "Ricardo",
      "Daniel",
      "Tiago",
      "Daniela",
      "Catarina",
      "Filipe",
      "Marta",
      "Gonçalo",
      "David",
      "Joana",
      "Vítor",
      "Nuno",
      "Mariana",
      "Hugo",
      "Sérgio",
      "João Pedro",
      "Beatriz",
      "Diogo",
      "Tomás",
      "Inês",
      "Mário",
      "Leonardo",
      "Lara",
      "João Paulo",
      "Carolina",
      "Matilde",
      "Francisco José",
      "Ricardo Jorge",
      "Ana Catarina",
      "Maria João",
      "João Miguel",
      "Ana Sofia",
      "Pedro Miguel",
      "Filipa",
      "Marco",
      "André Filipe",
      "Catarina Sofia",
      "Ana Beatriz",
      "João Tomás",
      "Diogo Filipe",
      "Maria Carolina",
      "Beatriz Sofia",
      "Gonçalo Manuel",
      "Inês Maria",
      "Rafael Miguel",
      "Mariana Joana",
      "Tiago André",
      "Ana Laura",
      "David João",
      "João David",
      "Francisco António",
      "Maria Inês",
      "Pedro Henrique",
      "Ana Clara",
      "Ricardo Alexandre",
      "Catarina Martins",
      "João Guilherme",
      "Diogo Fernandes",
      "Maria Teresa",
      "Beatriz Rodrigues",
      "Gonçalo Ferreira",
      "Inês Silva",
      "Rafael Oliveira",
      "Mariana Costa",
      "Tiago Santos",
      "Ana Lopes",
      "David Pereira",
      "João Sousa",
      "Francisco Mendes",
      "Maria Pinto",
      "Pedro Silva",
      "Pedro Silva",
      "Pedro Silva",
      "Pedro Silva",
      "Pedro Silva",
      "Pedro Silva",
      "Pedro Silva",
      "Pedro Silva",
      "Pedro Silva",
      "Pedro Silva",
      "Pedro Silva",
      "Pedro Silva",
      "Pedro Silva",
      "Pedro Silva",
      "Pedro Silva",
      "Pedro Silva",
      "Pedro Silva",
      "Pedro Silva",
      "Pedro Silva",
      "Pedro Silva",
      "Pedro Silva",
      "Pedro Silva",
      "Ana Oliveira"
    ]
  },
  getters: {
  },
  mutations: {
  },
  actions: {
  },
  modules: {
  }
})
